version: "3.9"

services:
  api:
    build: .
    container_name: got_api
    ports:
      - "5283:5283"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=got_db;Username=postgres;Password=postgres

  db:
    image: postgres:16
    container_name: got_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: got_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
